export const FETCH_DRINKS_REQUEST = "FETCH_DRINKS_REQUEST";
export const FETCH_DRINKS_SUCCESS = "FETCH_DRINKS_SUCCESS";
export const FETCH_DRINKS_ERROR = "FETCH_DRINKS_ERROR";
export const FETCH_DRINKS_SEARCH_SUCCESS = "FETCH_DRINKS_SEARCH_SUCCESS";
export const FETCH_SINGLE_DRINK_SUCCESS = "FETCH_SINGLE_DRINK_SUCCESS";
